# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
# Fabric Properties
# check these on https://fabricmc.net/develop/
# Mod Properties
mod_version=1.21.1-1.0.0
maven_group=io.github.codecraftplugin
archives_base_name=registry-lib
#Minecraft

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.9
#Fabric api
fabric_version=0.114.0+1.21.1
